[tool.black]
line-length = 88
target-version = ["py310"]
extend-exclude = ["build", "dist"]

[tool.isort]
profile = "black"
line_length = 88
skip = ["build", "dist"]

[tool.ruff]
line-length = 88
select = ["E", "F", "I"]
extend-exclude = ["build", "dist"]