[project]
name = "swarm-sandbox"
version = "0.1.0"
description = "Experimental repository for swarm intelligence simulations"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"
authors = [
    {name = "swarm-sandbox contributors"}
]
dependencies = []
